"""
Conference Flow - Système de gestion de conférence scientifique
Copyright (C) 2025 Olivier Farges olivier@olivier-farges.xyz

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

from datetime import datetime
import logging

from lxml import etree
from flask import current_app


class DOIXMLError(Exception):
    """Exception levée quand les données ne permettent pas de produire un XML valide"""
    pass


class DOIXMLGenerator:
    """Génère le XML DataCite kernel-4 pour l'enregistrement des DOI"""

    XMLNS = "http://datacite.org/schema/kernel-4"
    XSI = "http://www.w3.org/2001/XMLSchema-instance"
    SCHEMA_LOCATION = (
        "http://datacite.org/schema/kernel-4 "
        "http://schema.datacite.org/meta/kernel-4/metadata.xsd"
    )

    # Libellé libre de resourceType, associé à resourceTypeGeneral="Text"
    RESOURCE_TYPES = {
        'article': "Conference Paper",
        'wip': "Work in Progress",
        'poster': "Conference Poster",
    }
    DEFAULT_RESOURCE_TYPE = "Conference Paper"

    def __init__(self):
        self.logger = logging.getLogger(__name__)

    # ------------------------------------------------------------------
    # Point d'entrée
    # ------------------------------------------------------------------

    def generate_datacite_xml(self, communication):
        """
        Génère le XML DataCite d'une communication et le retourne sous
        forme de chaîne (sans déclaration XML).
        """
        return etree.tostring(
            self._build_tree(communication),
            pretty_print=True,
            encoding='unicode'
        )

    def generate_datacite_file(self, communication):
        """
        Génère le XML DataCite sous forme d'octets, avec déclaration XML
        et encodage UTF-8. C'est cette forme qui doit être livrée à l'Inist.
        """
        return etree.tostring(
            self._build_tree(communication),
            pretty_print=True,
            xml_declaration=True,
            encoding='UTF-8'
        )

    # ------------------------------------------------------------------
    # Construction de l'arbre
    # ------------------------------------------------------------------

    def _build_tree(self, communication):
        if not communication.doi:
            raise DOIXMLError(
                f"Communication {communication.id} : DOI absent"
            )
        if not communication.title:
            raise DOIXMLError(
                f"Communication {communication.id} : titre absent"
            )

        root = etree.Element(
            f"{{{self.XMLNS}}}resource",
            attrib={f"{{{self.XSI}}}schemaLocation": self.SCHEMA_LOCATION},
            nsmap={'xsi': self.XSI, None: self.XMLNS}
        )
        root.append(etree.Comment('Generated by Conference Flow'))

        self._add_identifier(root, communication)
        self._add_creators(root, communication)
        self._add_titles(root, communication)
        self._add_publisher(root)
        self._add_publication_year(root)
        self._add_resource_type(root, communication)
        self._add_subjects(root, communication)
        self._add_language(root)
        self._add_alternate_identifiers(root, communication)
        self._add_descriptions(root, communication)

        return root

    def _add_identifier(self, root, communication):
        identifier = etree.SubElement(
            root, "identifier", attrib={'identifierType': 'DOI'}
        )
        identifier.text = communication.doi

    def _add_creators(self, root, communication):
        authors = self._ordered_authors(communication)
        if not authors:
            raise DOIXMLError(
                f"Communication {communication.id} : aucun auteur"
            )

        creators = etree.SubElement(root, "creators")
        for author in authors:
            creator = etree.SubElement(creators, "creator")

            last_name = (author.last_name or '').strip()
            first_name = (author.first_name or '').strip()

            creator_name = etree.SubElement(
                creator, "creatorName", attrib={'nameType': 'Personal'}
            )
            creator_name.text = f"{last_name}, {first_name}".strip(', ')

            if first_name:
                etree.SubElement(creator, "givenName").text = first_name
            if last_name:
                etree.SubElement(creator, "familyName").text = last_name

            # ORCID : identifiant recommandé par DataCite
            if getattr(author, 'orcid', None):
                name_id = etree.SubElement(
                    creator, "nameIdentifier",
                    attrib={
                        'nameIdentifierScheme': 'ORCID',
                        'schemeURI': 'https://orcid.org'
                    }
                )
                name_id.text = f"https://orcid.org/{author.orcid}"

            # Toutes les affiliations de l'auteur
            for aff in (author.affiliations or []):
                label = self._format_affiliation(aff)
                if label:
                    etree.SubElement(creator, "affiliation").text = label

    def _add_titles(self, root, communication):
        titles = etree.SubElement(root, "titles")
        title = etree.SubElement(
            titles, "title",
            attrib={'{http://www.w3.org/XML/1998/namespace}lang': 'fr'}
        )
        title.text = communication.title.strip()

    def _add_publisher(self, root):
        etree.SubElement(root, "publisher").text = self._get_publisher()

    def _add_publication_year(self, root):
        etree.SubElement(root, "publicationYear").text = str(self._get_year())

    def _add_resource_type(self, root, communication):
        label = self.RESOURCE_TYPES.get(
            (communication.type or '').lower(),
            self.DEFAULT_RESOURCE_TYPE
        )
        resource_type = etree.SubElement(
            root, "resourceType", attrib={'resourceTypeGeneral': 'Text'}
        )
        resource_type.text = label

    def _add_subjects(self, root, communication):
        if not communication.keywords:
            return
        keywords = [
            k.strip() for k in communication.keywords.split(',') if k.strip()
        ]
        if not keywords:
            return
        subjects = etree.SubElement(root, "subjects")
        for keyword in keywords:
            subject = etree.SubElement(
                subjects, "subject",
                attrib={'{http://www.w3.org/XML/1998/namespace}lang': 'fr'}
            )
            subject.text = keyword

    def _add_language(self, root):
        # IETF BCP 47 / ISO 639-1, en minuscules
        etree.SubElement(root, "language").text = "fr"

    def _add_alternate_identifiers(self, root, communication):
        """
        Le schéma DataCite ne porte pas la page de destination du DOI.
        On enregistre malgré tout l'URL publique comme identifiant
        alternatif, à titre documentaire.
        """
        if not communication.public_url:
            return
        alternate_ids = etree.SubElement(root, "alternateIdentifiers")
        alt_id = etree.SubElement(
            alternate_ids, "alternateIdentifier",
            attrib={'alternateIdentifierType': 'URL'}
        )
        alt_id.text = communication.public_url

    def _add_descriptions(self, root, communication):
        entries = []
        if communication.abstract_fr:
            entries.append(('fr', communication.abstract_fr))
        if communication.abstract_en:
            entries.append(('en', communication.abstract_en))

        if not entries:
            return

        descriptions = etree.SubElement(root, "descriptions")
        for lang, text in entries:
            description = etree.SubElement(
                descriptions, "description",
                attrib={
                    'descriptionType': 'Abstract',
                    '{http://www.w3.org/XML/1998/namespace}lang': lang
                }
            )
            description.text = ' '.join(text.split())

    # ------------------------------------------------------------------
    # Utilitaires
    # ------------------------------------------------------------------

    def _ordered_authors(self, communication):
        """
        Retourne les auteurs dans l'ordre de author_order, dédoublonnés.

        La relation communication.authors ne garantit aucun ordre, et la
        table communication_authors contient des auteurs avec author_order
        à 0 et à 1 pour la même position.
        """
        from ..models import CommunicationAuthor

        associations = (
            CommunicationAuthor.query
            .filter_by(communication_id=communication.id)
            .order_by(CommunicationAuthor.author_order)
            .all()
        )

        authors = []
        seen = set()
        for assoc in associations:
            if assoc.user_id in seen or assoc.user is None:
                continue
            seen.add(assoc.user_id)
            authors.append(assoc.user)

        if not authors:
            authors = list(communication.authors or [])

        return authors

    def _format_affiliation(self, affiliation):
        """Libellé d'affiliation : nom complet, sigle entre parenthèses."""
        nom = (getattr(affiliation, 'nom_complet', None) or '').strip()
        sigle = (getattr(affiliation, 'sigle', None) or '').strip()

        if nom and sigle and sigle.lower() not in nom.lower():
            return f"{nom} ({sigle})"
        return nom or sigle

    def _get_publisher(self):
        """
        Lit l'organisateur depuis conference.yml en tolérant les deux
        formes rencontrées dans le code : chaîne ou dictionnaire.
        """
        conference = current_app.conference_config.get('conference', {})
        organizer = conference.get('organizer')

        if isinstance(organizer, dict):
            name = organizer.get('name')
        else:
            name = organizer

        return (name or "Société Française de Thermique").strip()

    def _get_year(self):
        conference = current_app.conference_config.get('conference', {})
        return conference.get('year', datetime.now().year)
